# fly.toml app configuration file generated for vladislav-skopenko-site-maker on 2024-08-03T11:32:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vladislav-skopenko-site-maker'
primary_region = 'waw'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
